package com.huanchengfly.tieba.post.utils

import android.content.Context
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import com.huanchengfly.tieba.post.App

object AppPrivacyManager {
    private const val PREFS_NAME = "privacy_settings"
    private const val KEY_PRIVACY_DATA = "privacy_data_json"
    private const val KEY_ACTIVE_TEMPLATE = "active_template"

    // Default template data
    val DEFAULT_TEMPLATE = PrivacyData(
        phoneImei = "000000000000000",
        model = "Pixel 8 Pro",
        brand = "Google",
        board = "husky",
        osVersion = "14",
        cuid = "baidutiebaapp00000000-0000-0000-0000-000000000000",
        cuidGalaxy2 = "baidutiebaapp00000000-0000-0000-0000-000000000000",
        c3Aid = "A00-0000000000000000000000000000000000000000-0000000000",
        oaid = "00000000-0000-0000-0000-000000000000",
        clientId = "wappc_0000000000000_000",
        netType = "1",
        androidId = "0000000000000000",
        firstInstallTime = "1700000000000",
        lastUpdateTime = "1700000000000",
        deviceScore = "4.25",
        scrDip = "3.0",
        scrH = "2400",
        scrW = "1080",
        zId = "00000000000000000000"
    )

    val REAL_DEVICE_TEMPLATE = PrivacyData(
        phoneImei = "000000000000000", // Android Q+ standard
        model = android.os.Build.MODEL,
        brand = android.os.Build.BRAND,
        board = android.os.Build.BOARD,
        osVersion = android.os.Build.VERSION.SDK_INT.toString(),
        cuid = "", // Dynamically generated by default if left blank
        cuidGalaxy2 = "",
        c3Aid = "",
        oaid = "",
        clientId = "",
        netType = "1",
        androidId = "",
        firstInstallTime = "",
        lastUpdateTime = "",
        deviceScore = "",
        scrDip = "",
        scrH = "",
        scrW = "",
        zId = ""
    )

    val SECURE_SANDBOX_TEMPLATE = PrivacyData(
        phoneImei = "000000000000000",
        model = "SM-G998B",
        brand = "samsung",
        board = "exynos2100",
        osVersion = "13",
        cuid = "99999999999999999999999999999999|V9999999999",
        cuidGalaxy2 = "99999999999999999999999999999999|V9999999999",
        c3Aid = "A00-9999999999999999999999999999999999999999-9999999999",
        oaid = "99999999-9999-9999-9999-999999999999",
        clientId = "wappc_1700000000000_999",
        netType = "1",
        androidId = "9999999999999999",
        firstInstallTime = "1650000000000",
        lastUpdateTime = "1680000000000",
        deviceScore = "3.85",
        scrDip = "4.0",
        scrH = "3200",
        scrW = "1440",
        zId = "99999999999999999999"
    )

    data class PrivacyData(
        var phoneImei: String = "",
        var model: String = "",
        var brand: String = "",
        var board: String = "",
        var osVersion: String = "",
        var cuid: String = "",
        var cuidGalaxy2: String = "",
        var c3Aid: String = "",
        var oaid: String = "",
        var clientId: String = "",
        var netType: String = "1",
        var androidId: String = "",
        var firstInstallTime: String = "",
        var lastUpdateTime: String = "",
        var deviceScore: String = "",
        var scrDip: String = "",
        var scrH: String = "",
        var scrW: String = "",
        var zId: String = ""
    )

    data class CustomTemplate(
        val name: String,
        val data: PrivacyData
    )

    private val gson = Gson()

    private fun getPrefs(): android.content.SharedPreferences {
        return App.INSTANCE.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    }

    fun getActiveTemplateName(): String {
        return getPrefs().getString(KEY_ACTIVE_TEMPLATE, "default") ?: "default"
    }

    fun setActiveTemplateName(name: String) {
        getPrefs().edit().putString(KEY_ACTIVE_TEMPLATE, name).apply()
    }

    fun getPrivacyData(): PrivacyData {
        val template = getActiveTemplateName()
        return when (template) {
            "default" -> DEFAULT_TEMPLATE
            "real_device" -> getMergedRealDeviceData()
            "secure" -> SECURE_SANDBOX_TEMPLATE
            else -> {
                // Load from custom templates
                val templates = getCustomTemplates()
                templates.find { it.name == template }?.data ?: DEFAULT_TEMPLATE
            }
        }
    }

    private fun getMergedRealDeviceData(): PrivacyData {
        val data = REAL_DEVICE_TEMPLATE.copy()
        // Compute dynamic defaults for real device where they are blank
        if (data.cuid.isBlank()) data.cuid = CuidUtils.getNewCuid()
        if (data.cuidGalaxy2.isBlank()) data.cuidGalaxy2 = CuidUtils.getNewCuid()
        if (data.c3Aid.isBlank()) data.c3Aid = UIDUtil.getAid()
        if (data.oaid.isBlank()) data.oaid = App.Config.encodedOAID.ifBlank { "00000000-0000-0000-0000-000000000000" }
        if (data.clientId.isBlank()) data.clientId = ClientUtils.clientId ?: RetrofitTiebaApi.randomClientId
        if (data.androidId.isBlank()) data.androidId = UIDUtil.getAndroidId("0000000000000000")
        if (data.firstInstallTime.isBlank()) data.firstInstallTime = App.Config.appFirstInstallTime.toString()
        if (data.lastUpdateTime.isBlank()) data.lastUpdateTime = App.Config.appLastUpdateTime.toString()
        if (data.deviceScore.isBlank()) data.deviceScore = DeviceUtils.getDeviceScore().toString()
        if (data.scrDip.isBlank()) data.scrDip = App.ScreenInfo.DENSITY.toString()
        if (data.scrH.isBlank()) data.scrH = getScreenHeightValue().toString()
        if (data.scrW.isBlank()) data.scrW = getScreenWidthValue().toString()
        if (data.zId.isBlank()) data.zId = AccountUtil.getAccountInfo { zid }.orEmpty()
        return data
    }

    private fun getScreenWidthValue(): Int {
        return runCatching { App.INSTANCE.resources.displayMetrics.widthPixels }.getOrDefault(1080)
    }

    private fun getScreenHeightValue(): Int {
        return runCatching { App.INSTANCE.resources.displayMetrics.heightPixels }.getOrDefault(2400)
    }

    fun getCustomTemplates(): List<CustomTemplate> {
        val json = getPrefs().getString(KEY_PRIVACY_DATA, null) ?: return emptyList()
        return try {
            val type = object : TypeToken<List<CustomTemplate>>() {}.type
            gson.fromJson(json, type) ?: emptyList()
        } catch (e: Exception) {
            emptyList()
        }
    }

    fun saveCustomTemplate(name: String, data: PrivacyData) {
        val templates = getCustomTemplates().toMutableList()
        templates.removeAll { it.name == name }
        templates.add(CustomTemplate(name, data))
        val json = gson.toJson(templates)
        getPrefs().edit().putString(KEY_PRIVACY_DATA, json).apply()
    }

    fun deleteCustomTemplate(name: String) {
        val templates = getCustomTemplates().toMutableList()
        templates.removeAll { it.name == name }
        val json = gson.toJson(templates)
        getPrefs().edit().putString(KEY_PRIVACY_DATA, json).apply()
        if (getActiveTemplateName() == name) {
            setActiveTemplateName("default")
        }
    }

    // Helper functions to get masked fields
    fun getPhoneImei(context: Context): String {
        val valStr = getPrivacyData().phoneImei
        return valStr.ifBlank { "000000000000000" }
    }

    fun getModel(): String {
        val valStr = getPrivacyData().model
        return valStr.ifBlank { android.os.Build.MODEL }
    }

    fun getBrand(): String {
        val valStr = getPrivacyData().brand
        return valStr.ifBlank { android.os.Build.BRAND }
    }

    fun getBoard(): String {
        val valStr = getPrivacyData().board
        return valStr.ifBlank { android.os.Build.BOARD }
    }

    fun getOsVersion(): String {
        val valStr = getPrivacyData().osVersion
        return valStr.ifBlank { android.os.Build.VERSION.SDK_INT.toString() }
    }

    fun getCuid(): String {
        val valStr = getPrivacyData().cuid
        return valStr.ifBlank { CuidUtils.getNewCuid() }
    }

    fun getCuidGalaxy2(): String {
        val valStr = getPrivacyData().cuidGalaxy2
        return valStr.ifBlank { CuidUtils.getNewCuid() }
    }

    fun getC3Aid(): String {
        val valStr = getPrivacyData().c3Aid
        return valStr.ifBlank { UIDUtil.getAid() }
    }

    fun getOaid(): String {
        val valStr = getPrivacyData().oaid
        return valStr.ifBlank { App.Config.encodedOAID.ifBlank { "00000000-0000-0000-0000-000000000000" } }
    }

    fun getClientId(): String {
        val valStr = getPrivacyData().clientId
        return valStr.ifBlank { ClientUtils.clientId ?: RetrofitTiebaApi.randomClientId }
    }

    fun getNetType(): String {
        val valStr = getPrivacyData().netType
        return valStr.ifBlank { "1" }
    }

    fun getAndroidId(defaultValue: String = "0000000000000000"): String {
        val valStr = getPrivacyData().androidId
        return valStr.ifBlank { UIDUtil.getAndroidId(defaultValue) }
    }

    fun getFirstInstallTime(): Long {
        val valStr = getPrivacyData().firstInstallTime
        return valStr.toLongOrNull() ?: App.Config.appFirstInstallTime
    }

    fun getLastUpdateTime(): Long {
        val valStr = getPrivacyData().lastUpdateTime
        return valStr.toLongOrNull() ?: App.Config.appLastUpdateTime
    }

    fun getDeviceScore(): Float {
        val valStr = getPrivacyData().deviceScore
        return valStr.toFloatOrNull() ?: DeviceUtils.getDeviceScore()
    }

    fun getScrDip(): Double {
        val valStr = getPrivacyData().scrDip
        return valStr.toDoubleOrNull() ?: App.ScreenInfo.DENSITY.toDouble()
    }

    fun getScrH(): Int {
        val valStr = getPrivacyData().scrH
        return valStr.toIntOrNull() ?: getScreenHeightValue()
    }

    fun getScrW(): Int {
        val valStr = getPrivacyData().scrW
        return valStr.toIntOrNull() ?: getScreenWidthValue()
    }

    fun getZId(): String {
        val valStr = getPrivacyData().zId
        return valStr.ifBlank { AccountUtil.getAccountInfo { zid }.orEmpty() }
    }
}
